language: rust

env:
  global:
    - secure: s8kMEgTtxFlv//89l3e/898UIS3pSgCI1IiLfYNfyTtRqgPGGcf8+F2jBb2jR/BYAls3lYVOftVz1dYJY6Cnsdv2xpLX3A9RS+RpyRCOUtdnVuRRI4m9FdVpqGmml4OjrF3TsIBOA94DRku+9ucTq59kjYP749uEQbwm3mASaOVztl3hB+gvPEbtrEcucz6qBBOx1Dhrwl2iIJvDgtXnB9otnDrwiN4cYnDg4UNIWZmNDahOyUTBvS9J3fx14rIAneyIADzbSgfbLdi6tTzoFJ9v2jOTfjP8uo6Kf9eEcOA29OrVjYMQnwoocJjBii2P6tAXzFMievqh6sWLZaHPsO9axkkiJfz5EVSoOK9unbRVp5IGoO8SboZp/Xxhn9xUo5Aw6qM+jdqgm+/7WK7Ilv6oT6FpYvMhioW6Z7GV15fxRt8F3y+219oK16q3wekSS68W5e6C1k/8Bf/T0y5xIfgbzMBZgg+FuDH9/QZ69G3mqJFDzY0XkdWrE7To+pw2bCt1I8a+zJkJqB5fAlXypvv+nd/mABPujTr5uK1G5BXUtLrtldco6lKTWdsYL7ou10D3XjgzmkFJhdu8hFOMKcKJeYg3wxqlkPjFrYgsi3lRZhHrywQVScdLd3dxsRuI8xXkVpgTwLmLKz7cVxE2X7MlsHZft/34fhT0X4pjuVE=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
